@orangeHRM-Admin-organization-operations
Feature: orangeHRM Admin organization operations

  Background:
    Given I open ebay with user ORANGEHRM and password ORANGEHRM
    And I open "Admin" from the menu

  @orangeHRM-Admin-organization-structure
  Scenario: orangeHRM Admin organization structure
    When I click on "Organization " from the top bar
    Then I click on "Structure" from the top bar
    And I click on "Edit" Button
    Then I delete the tree node content
    When I click on " Add "
    Then I fill the "Unit Id" with "Name"
    And I fill the "Name" with "Lotfi Otai"
    Then I click on " Save "
    When I click on " Add "
    Then I fill the "Unit Id" with "Phone Number"
    And I fill the "Name" with "phoneNumber"
    Then I click on " Save "
    When I click on " Add "
    Then I fill the "Unit Id" with "Email Address"
    And I fill the "Name" with "emailAddress"
    Then I click on " Save "
    When I click on " Add "
    Then I fill the "Unit Id" with "Location"
    And I fill the "Name" with "Centre Urbain Nord, Tunisie"
    Then I click on " Save "
    When I click on " Add "
    Then I fill the "Unit Id" with "GitHub"
    And I fill the "Name" with "GitHub Url"
    Then I click on " Save "
    When I click on " Add "
    Then I fill the "Unit Id" with "Linkedin"
    And I fill the "Name" with "Linkedin Url"
    Then I click on " Save "
    When I click on " Add "
    And I fill the "Name" with "Career"
    Then I click on " Save "
    When I click on add button from the node "Career"
    And I fill the "Name" with "FORVIA Inspiring Mobility"
    Then I click on " Save "
    When I click on add button from the node "Career"
    And I fill the "Name" with "Dedagroup"
    Then I click on " Save "
    When I click on add button from the node "Career"
    And I fill the "Name" with "Zedonk."
    Then I click on " Save "
    When I click on " Add "
    Then I fill the "Unit Id" with "Position"
    And I fill the "Name" with "Engineer"
    Then I click on " Save "
    When I click on add button from the node "Position"
    Then I fill the "Unit Id" with "SDET"
    And I fill the "Name" with "Software Development Engineer in Test"
    Then I click on " Save "
    When I click on add button from the node "Position"
    Then I fill the "Name" with "Full Stack QA Developer"
    And I click on " Save "
    When I click on add button from the node "Position"
    Then I fill the "Name" with "QA Automation Engineer"
    And I click on " Save "
    When I click on add button from the node "Position"
    Then I fill the "Name" with "QA Specialist"
    And I click on " Save "
    When I click on " Add "
    And I fill the "Name" with "Programming Languages"
    Then I click on " Save "
    When I click on add button from the node "Programming Languages"
    Then I fill the "Name" with "Python"
    And I click on " Save "
    When I click on add button from the node "Programming Languages"
    Then I fill the "Name" with "Java"
    And I click on " Save "
    When I click on add button from the node "Programming Languages"
    Then I fill the "Name" with "C#"
    And I click on " Save "
    When I click on " Add "
    And I fill the "Name" with "Skills"
    Then I click on " Save "
    When I click on add button from the node "Skills"
    Then I fill the "Name" with "Front End Skills"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Front End Skills"
    Then I fill the "Name" with "AI"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Front End Skills"
    Then I fill the "Name" with "Healenium"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Front End Skills"
    Then I fill the "Name" with "Selenium"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Front End Skills"
    Then I fill the "Name" with "Gherkin"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Front End Skills"
    Then I fill the "Name" with "BDD"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Front End Skills"
    Then I fill the "Name" with "Cucumber"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Front End Skills"
    Then I fill the "Name" with "Specflow"
    And I click on " Save "
    When I click on add button from the node "Skills"
    Then I fill the "Name" with "Back End Skills"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Back End Skills"
    Then I fill the "Name" with "Rest Assured"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Back End Skills"
    Then I fill the "Name" with "Swagger UI"
    And I click on " Save "
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Back End Skills"
    Then I fill the "Name" with "Postman"
    And I click on " Save "
    Then I scroll to find "Skills"
    When I click on add button from the node "Skills"
    Then I fill the "Name" with "Common Skills"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "Common Skills"
    When I click on add button from the node "Common Skills"
    Then I fill the "Name" with "TestNG"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "Common Skills"
    When I click on add button from the node "Common Skills"
    Then I fill the "Name" with "JUnit"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "Common Skills"
    When I click on add button from the node "Common Skills"
    Then I fill the "Name" with "JUnit5"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "Common Skills"
    When I click on add button from the node "Common Skills"
    Then I fill the "Name" with "NUnit"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    When I click on add button from the node "Skills"
    Then I fill the "Name" with "CI/CD"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    When I click on add button from the node "CI/CD"
    Then I fill the "Name" with "Jenkins"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "CI/CD"
    When I click on add button from the node "CI/CD"
    Then I fill the "Name" with "Git"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "CI/CD"
    When I click on add button from the node "CI/CD"
    Then I fill the "Name" with "Git Hub"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "CI/CD"
    When I click on add button from the node "CI/CD"
    Then I fill the "Name" with "Gradle"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "CI/CD"
    When I click on add button from the node "CI/CD"
    Then I fill the "Name" with "Maven"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "CI/CD"
    When I click on add button from the node "CI/CD"
    Then I fill the "Name" with "SonarQube"
    And I click on " Save "
    Then I scroll to find "Skills"
    And I click on the toggle node from "Skills"
    Then I scroll to find "CI/CD"
    When I click on add button from the node "CI/CD"
    Then I fill the "Name" with "Bitbucket"
    And I click on " Save "
    Then I scroll to find " Add "
    When I click on " Add "
    And I fill the "Name" with "Git Hub Projects"
    Then I click on " Save "
    Then I scroll to find "Git Hub Projects"
    When I click on add button from the node "Git Hub Projects"
    Then I fill the "Name" with "Front End Projects"
    And I click on " Save "
    Then I scroll to find "Git Hub Projects"
    And I click on the toggle node from "Git Hub Projects"
    Then I scroll to find "Front End Projects"
    When I click on add button from the node "Front End Projects"
    Then I fill the "Name" with "SeleniumCucumberBDDGradle.EbayTestCraft"
    And I click on " Save "
    Then I scroll to find "Git Hub Projects"
    And I click on the toggle node from "Git Hub Projects"
    Then I scroll to find "Front End Projects"
    When I click on add button from the node "Front End Projects"
    Then I fill the "Name" with "SeleniumCucumberBDDGradle.orangeHRMTestCraft"
    And I click on " Save "
    Then I scroll to find "Git Hub Projects"
    And I click on the toggle node from "Git Hub Projects"
    Then I scroll to find "Front End Projects"
    When I click on add button from the node "Front End Projects"
    Then I fill the "Name" with "SeleniumJUnit5.JoraniUITestCraft"
    And I click on " Save "
    Then I scroll to find "Git Hub Projects"
    When I click on add button from the node "Git Hub Projects"
    Then I fill the "Name" with "Back End Project"
    And I click on " Save "
    Then I scroll to find "Git Hub Projects"
    And I click on the toggle node from "Git Hub Projects"
    Then I scroll to find "Back End Project"
    When I click on add button from the node "Back End Project"
    Then I fill the "Name" with "RestAssuredTestNGGradle.SwaggerUIAPITest"
    And I click on " Save "
    Then I scroll the Dashboard page
    And I click on the toggle node from "Career"
    And I click on the toggle node from "Position"
    And I click on the toggle node from "Programming Languages"
    And I click on the toggle node from "Skills"
    And I click on the toggle node from "Front End Skills"
    And I click on the toggle node from "Back End Skills"
    And I click on the toggle node from "Common Skills"
    And I click on the toggle node from "CI/CD"
    And I click on the toggle node from "Git Hub Projects"
    And I click on the toggle node from "Front End Projects"
    And I click on the toggle node from "Back End Project"
    Then I scroll the Dashboard page
    Then I scroll to the top of the page