name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Run-Actions
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ".*build.gradle$" 
          VALIDATE_ALL_CODEBASE: false 
          VALIDATE_JAVA: true  
          VALIDATE_GHERKIN: true  
          JAVAC_DEFAULT_VERSION: 17  
          LINTER_RULES_PATH: .github/linter-rules  
