name: Run Automated Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Gradle (for wrapper generation)
        run: |
          curl -sSL https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Tests with Gradle
        run: ./gradlew clean test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4  
        with:
          name: test-reports
          path: build/reports/tests/test/
  
  test-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Test Reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: test-reports

      - name: Display Test Report Files
        run: ls -R test-reports

      - name: Upload Test Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-test-reports
          path: test-reports
