name: Run Automated Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Gradle (for wrapper generation)
        run: |
          curl -sSL https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Ensure Test Report Directory Exists
        run: mkdir -p build/reports/tests/test/

      - name: Run Tests with Gradle
        run: ./gradlew clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test/

  reports:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: test-reports

      - name: Ensure Test Report Directory Exists
        run: mkdir -p test-reports

      - name: Upload Test Report as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-reports
